# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-z0ydJMtSONM5qlKdE6KL8laig12fRSm
"""

import pandas as pd

#To read/write data from Google Drive:
#Reference: https://colab.research.google.com/notebooks/io.ipynb#scrollTo=u22w3BFiOveAå
from google.colab import drive

#Mount disk for project
drive.mount('/content/drive')

#Load xls file from drive
xls = pd.ExcelFile('/content/drive/MyDrive/Colab Notebooks/Savukoski kirkonkyla (1).xlsx')

#Read specific page "Observation data" from the xsl
df = pd.read_excel(xls, 'Observation data')

#Verify dataset import
df

#Remove unwanted column
del df["Time"]
del df["Time zone"]

#Groupby month and calculate mean and std from the dataset
#Moyenne & Ecart type
df.groupby("m").agg(['mean', 'std'])

#Maximum per month
df.groupby("m").max()

#Minimum per month
df.groupby("m").min()

#Maximum per year
df.groupby("Year").max()

#Minimum per year
df.groupby("Year").min()

df[df["m"] == 1].plot(x="d", y="Maximum temperature (degC)");
df[df["m"] == 1].plot(x="d", y="Minimum temperature (degC)");

df[df["m"] == 2].plot(x="d", y="Maximum temperature (degC)");
df[df["m"] == 2].plot(x="d", y="Minimum temperature (degC)");

df[df["m"] == 3].plot(x="d", y="Maximum temperature (degC)");
df[df["m"] == 3].plot(x="d", y="Minimum temperature (degC)");

df[df["m"] == 4].plot(x="d", y="Maximum temperature (degC)");
df[df["m"] == 4].plot(x="d", y="Minimum temperature (degC)");

df[df["m"] == 5].plot(x="d", y="Maximum temperature (degC)");
df[df["m"] == 5].plot(x="d", y="Minimum temperature (degC)");

df[df["m"] == 6].plot(x="d", y="Maximum temperature (degC)");
df[df["m"] == 6].plot(x="d", y="Minimum temperature (degC)");

df[df["m"] == 7].plot(x="d", y="Maximum temperature (degC)");
df[df["m"] == 7].plot(x="d", y="Minimum temperature (degC)");

df[df["m"] == 8].plot(x="d", y="Maximum temperature (degC)");
df[df["m"] == 8].plot(x="d", y="Minimum temperature (degC)");

df[df["m"] == 9].plot(x="d", y="Maximum temperature (degC)");
df[df["m"] == 9].plot(x="d", y="Minimum temperature (degC)");

df[df["m"] == 10].plot(x="d", y="Maximum temperature (degC)");
df[df["m"] == 10].plot(x="d", y="Minimum temperature (degC)");

df[df["m"] == 11].plot(x="d", y="Maximum temperature (degC)");
df[df["m"] == 11].plot(x="d", y="Minimum temperature (degC)");

df[df["m"] == 12].plot(x="d", y="Maximum temperature (degC)");
df[df["m"] == 12].plot(x="d", y="Minimum temperature (degC)");

#To read/write data from Google Drive:
#Reference: https://colab.research.google.com/notebooks/io.ipynb#scrollTo=u22w3BFiOveAå
from google.colab import drive

#Mount disk for project
drive.mount('/content/drive')

#Load xls file from drive
xls = pd.ExcelFile('/content/drive/MyDrive/Colab Notebooks/Climat.xlsx')

#Read specific page "Observation data" from the xsl
df = pd.read_excel(xls, 'Observation data')